# Site settings
title: Blog of Laoniu85
description: > # this means to ignore newlines until "baseurl:"
  I'm tring to write a blog with github, I write it with a template from jekyll.org.
baseurl: /
url: "http://laoniu85.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  laoniu85@163.com

# Build settings
markdown: kramdown

